<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="DESKTOP-I3EUG8M" ignored="3" name="Default test" tests="1" failures="0" timestamp="2021-01-28T10:01:29 IST" time="0.075" errors="0">
  <testcase name="@BeforeTest bt" time="0.011" classname="appium.framework.Demo1">
    <failure type="java.lang.NullPointerException">
      <![CDATA[java.lang.NullPointerException
at java.util.Hashtable.get(Unknown Source)
at java.util.Properties.getProperty(Unknown Source)
at appium.framework.Capability.capabilities(Capability.java:87)
at appium.framework.Demo1.bt(Demo1.java:34)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:132)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:61)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:366)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:320)
at org.testng.TestRunner.invokeTestConfigurations(TestRunner.java:617)
at org.testng.TestRunner.beforeRun(TestRunner.java:607)
at org.testng.TestRunner.run(TestRunner.java:578)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1218)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
at org.testng.TestNG.runSuites(TestNG.java:1069)
at org.testng.TestNG.run(TestNG.java:1037)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- @BeforeTest bt -->
  <testcase name="testCase4" time="0.0" classname="appium.framework.Demo1">
    <skipped/>
  </testcase> <!-- testCase4 -->
  <testcase name="testCase1" time="0.0" classname="appium.framework.Demo1">
    <ignored/>
  </testcase> <!-- testCase1 -->
  <testcase name="testCase2" time="0.0" classname="appium.framework.Demo1">
    <ignored/>
  </testcase> <!-- testCase2 -->
  <testcase name="testCase3" time="0.0" classname="appium.framework.Demo1">
    <ignored/>
  </testcase> <!-- testCase3 -->
</testsuite> <!-- Default test -->
